import * as vscode from "vscode";

export interface LeaderboardRow {
  rank: number;
  name: string;
  todayMinutes: number;
  streak: number;
  focusScore: number;
  avatar: string;
  source?: string;
}

export interface PublishLeaderboardResult {
  gistId: string;
  url: string;
}

export async function loadLeaderboardRows(local: LeaderboardRow): Promise<LeaderboardRow[]> {
  const config = vscode.workspace.getConfiguration("devToolkit.sessionTracker");
  const leaderboardConfig = config.get<{
    gistId?: string;
    teamGistIds?: string[];
    name?: string;
    avatar?: string;
  }>("leaderboard", {});
  const ids = [
    leaderboardConfig?.gistId,
    ...(leaderboardConfig?.teamGistIds ?? []),
  ].filter((id): id is string => Boolean(id?.trim()));

  const rows = [local];
  for (const id of ids) {
    const row = await fetchGistRow(id).catch(() => undefined);
    if (row) {
      rows.push(row);
    }
  }

  return rows
    .sort((a, b) => b.todayMinutes - a.todayMinutes || b.focusScore - a.focusScore)
    .map((row, index) => ({ ...row, rank: index + 1 }));
}

export async function publishLeaderboardStat(
  local: LeaderboardRow,
  tokenFromSecret?: string
): Promise<PublishLeaderboardResult> {
  const config = vscode.workspace.getConfiguration("devToolkit.sessionTracker");
  const leaderboardConfig = config.get<{ gistId?: string; token?: string }>("leaderboard", {});
  const token = leaderboardConfig?.token || tokenFromSecret;
  if (!token) {
    throw new Error("Connect GitHub first, or set devToolkit.sessionTracker.leaderboard.token before publishing.");
  }
  const payload = { ...local, updatedAt: new Date().toISOString() };
  const files = {
    "focusforge.json": {
      content: JSON.stringify(payload, null, 2),
    },
    "teamleaderboard.md": {
      content: renderLeaderboardMarkdown([payload]),
    },
  };
  const body = {
    description: "FocusForge daily productivity stat",
    files,
  };
  const hasGist = Boolean(leaderboardConfig?.gistId?.trim());
  const createBody = hasGist ? body : { ...body, public: false };
  const res = await fetch(
    hasGist
      ? `https://api.github.com/gists/${leaderboardConfig.gistId?.trim()}`
      : "https://api.github.com/gists",
    {
      method: hasGist ? "PATCH" : "POST",
      headers: {
        Accept: "application/vnd.github+json",
        Authorization: `Bearer ${token}`,
        "X-GitHub-Api-Version": "2022-11-28",
      },
      body: JSON.stringify(createBody),
    }
  );
  if (!res.ok) {
    const message = await res.text().catch(() => "");
    throw new Error(`GitHub Gist publish failed: ${res.status}${message ? ` ${message}` : ""}`);
  }
  const gist = (await res.json()) as { id?: string; html_url?: string };
  if (!hasGist && gist.id) {
    const nextConfig = { ...leaderboardConfig, gistId: gist.id };
    await config.update("leaderboard", nextConfig, vscode.ConfigurationTarget.Global);
  }
  return {
    gistId: gist.id || leaderboardConfig.gistId || "",
    url: gist.html_url || (gist.id ? `https://gist.github.com/${gist.id}` : ""),
  };
}

export function renderLeaderboardMarkdown(rows: Array<Partial<LeaderboardRow> & { updatedAt?: string }>): string {
  const sorted = rows
    .slice()
    .sort((a, b) => Number(b.todayMinutes ?? 0) - Number(a.todayMinutes ?? 0) || Number(b.focusScore ?? 0) - Number(a.focusScore ?? 0));
  const lines = [
    "# FocusForge Team Leaderboard",
    "",
    "| Rank | Name | Today | Streak | Focus | Updated |",
    "| ---: | --- | ---: | ---: | ---: | --- |",
  ];
  sorted.forEach((row, index) => {
    lines.push(
      `| ${index + 1} | ${escapeMarkdown(row.name || "Teammate")} | ${Number(row.todayMinutes ?? 0)}m | ${Number(row.streak ?? 0)}d | ${Number(row.focusScore ?? 0)} | ${escapeMarkdown(row.updatedAt ? new Date(row.updatedAt).toLocaleString() : "")} |`
    );
  });
  lines.push("", "Generated by FocusForge.");
  return lines.join("\n");
}

export async function fetchGistMarkdown(id: string): Promise<string | undefined> {
  const res = await fetch(`https://api.github.com/gists/${id.trim()}`, {
    headers: {
      Accept: "application/vnd.github+json",
      "X-GitHub-Api-Version": "2022-11-28",
    },
  });
  if (!res.ok) {
    return undefined;
  }
  const gist = (await res.json()) as { files?: Record<string, { content?: string }> };
  return gist.files?.["teamleaderboard.md"]?.content;
}

async function fetchGistRow(id: string): Promise<LeaderboardRow | undefined> {
  const res = await fetch(`https://api.github.com/gists/${id.trim()}`, {
    headers: {
      Accept: "application/vnd.github+json",
      "X-GitHub-Api-Version": "2022-11-28",
    },
  });
  if (!res.ok) {
    return undefined;
  }
  const gist = (await res.json()) as {
    files?: Record<string, { content?: string }>;
    owner?: { login?: string };
  };
  const content =
    gist.files?.["focusforge.json"]?.content ??
    Object.values(gist.files ?? {})[0]?.content;
  if (!content) {
    return undefined;
  }
  const parsed = JSON.parse(content) as Partial<LeaderboardRow>;
  return {
    rank: 0,
    name: parsed.name || gist.owner?.login || "Teammate",
    todayMinutes: Number(parsed.todayMinutes ?? 0),
    streak: Number(parsed.streak ?? 0),
    focusScore: Number(parsed.focusScore ?? 0),
    avatar: parsed.avatar || "◆",
    source: id,
  };
}

function escapeMarkdown(value: unknown): string {
  return String(value ?? "").replace(/[\\|]/g, "\\$&").replace(/\n/g, " ");
}
